package org.app.aiservice.service;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.app.aiservice.model.Activity;
import org.app.aiservice.model.Recommendation;
import org.app.aiservice.repository.RecommendationRepository;
import org.springframework.amqp.rabbit.annotation.RabbitListener;
import org.springframework.amqp.rabbit.core.RabbitTemplate;
import org.springframework.stereotype.Service;


@Service
@RequiredArgsConstructor
@Slf4j
public class ActivityMessageListener {

    public static final String QUEUE_NAME = "activityQueue";
    private final ActivityAIService aiService;
    private final RecommendationRepository repository;

    @RabbitListener(queues = QUEUE_NAME)
    public void activityListener(Activity activity) {
        log.info("you have consumed the following activity: {}", activity.getId());
        log.info("this recommendation has been generated by ai service : {}", aiService.generateRecommendation(activity));
        Recommendation recommendation = aiService.generateRecommendation(activity);
        repository.save(recommendation);
    }

}
