# Use postgres/example user/password credentials

services:

  config-service:
    image: mantichanouar/config-service
    container_name: config-service
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=classpath:/config
    networks:
      fitness-app:

  discovery-service:
    image: mantichanouar/discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
    networks:
      fitness-app:

  user-service:
    image: mantichanouar/user-service
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-service:8888/
    networks:
      fitness-app:
    depends_on:
      - config-service
      - discovery-service
      - user-db

  activity-service:
    image: mantichanouar/activity-service
    container_name: activity-service
    ports:
      - "8082:8082"
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-service:8888/
    networks:
      fitness-app:
    depends_on:
      - config-service
      - discovery-service
      - mongo
      - rabbit-mq

  ai-service:
    image: mantichanouar/ai-service
    container_name: ai-service
    ports:
      - "8083:8083"
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-service:8888/
    networks:
      fitness-app:
    depends_on:
      - config-service
      - discovery-service
      - mongo
      - rabbit-mq

  api-gateway:
    image: mantichanouar/api-gateway
    container_name: api-gateway
    ports:
      - "9999:9999"
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-service:8888/
    networks:
      fitness-app:
    depends_on:
      - user-service
      - keycloak
      - activity-service
      - ai-service


  user-db:
    image: postgres
    restart: always
    container_name: user-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user-db

    volumes:
      - user-db:/var/lib/postgresql/data
    networks:
      fitness-app:

  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
    networks:
      fitness-app:

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8181:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      fitness-app:

  rabbit-mq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      fitness-app:

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.2.5
    command: start-dev
    ports:
      - "8282:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      fitness-app:




volumes:
  user-db:
  mongo-data:
  keycloak_data:
networks:
  fitness-app: