spring:
  application:
    name: ai-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888/
#gemini:
#  api:
#    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=
#    key:  AIzaSyDc7TKfaPl-WpQWsQkZdTSiL3ri-FA_TZU