spring:
  data:
    mongodb:
      url: mongodb://root:example@localhost:27017/fitnessActivities?authSource=admin
  rabbitmq:
    host: localhost
    port: 5672
    stream:
      username: guest
      password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
