spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/fitness-oauth2/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
