spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: USER-SERVICE
              uri: lb://USER-SERVICE
              predicates:
                - Path= /api/v1/users/**
            - id: AI-SERVICE
              uri: lb://AI-SERVICE
              predicates:
                - Path= /api/v1/recommendations/**
            - id: ACTIVITY-SERVICE
              uri: lb://ACTIVITY-SERVICE
              predicates:
                - Path= /api/v1/activities/**
server:
  port: 9999